# Generated by Django 5.0.7 on 2024-07-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_queue', '0002_alter_specificqueue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificqueue',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
