# Generated by Django 5.0.7 on 2024-07-23 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_queue', '0003_specificqueue_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuemember',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.CreateModel(
            name='AnswerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('time', models.TimeField()),
                ('specific_queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_queue.specificqueue')),
            ],
        ),
    ]
